### ISSUE TITLE
Helix and Oh My Posh Themes.

### ISSUE THREAD

**Issue by dreisss** [Ballerini-Theme/ballerini-theme#10]
Links to repositories: [Helix](https://github.com/dreisss/helix), [Oh My Posh](https://github.com/dreisss/oh-my-posh).

**Comment by AlphaLawless** [comment]
Thank you for the wonderful contribution, however, in the [team](https://github.com/dreisss/helix#team) session you need to add those who contributed (yours if it's just you who participated).

**Comment by dreisss** [comment]
Oh, ok, I will do it!

edit: changes made [helix](https://github.com/dreisss/helix) [oh-my-posh](https://github.com/dreisss/oh-my-posh)

**Comment by AlphaLawless** [comment]
You have been invited to two teams, Helix and Oh My Posh. Accept the invitation and transfer the themes to organization.

**Comment by dreisss** [comment]
I transferred the repos and created a pull request to update README: #13

**Comment by AlphaLawless** [comment]
Nice! I'm going to close this issue now
